general:
  scratch_directory: "./scratch"
  feature_extraction_filelist: "./file_lists/jgtzan_folds/jamendo_gtzan_meta.txt"
  train_filelist: "./file_lists/jgtzan_folds/jgtzan_f1_train.txt"
  test_filelist: "./file_lists/jgtzan_folds/jgtzan_f1_test.txt"
  predict_file: "./scratch/predict"
  label_file: "./file_lists/jgtzan_folds/jgtzan_f1_evaluate.txt"
  extract_accum_tag: ""
  train_test_tag: ""
  dft:
    len: 2048
    window_size: 1024
    window_step: 512
  sample_rate: 22050 #usar isso!!!!!!!! resampling é muito lento..
  mono: True
  zero_pad_resampling: True
  output_parameters: False

steps:
  extract_features: False
  aggregate_features: True
  train: False
  test: False
  evaluate: False

#Feature extraction parameters
feature_extraction:
  output_buffer_size: 100
  extractor: 'bandwise'
  worker_extractors: 1

bandwise_extraction:
  scale: 'one'
  number_of_bands: 30
  also_one_band: True
  discard_bin_zero: True
  threshold_cut: None

#Feature aggregation parameters
feature_aggregation:
  aggregator: "simple"
  aggregated_output: "feature_matrix"

simple_aggregation:
  texture_windows: True
  texture_window_length: 80
  tw_buffer_size: 100
  tw_workers: 1
  mean: True
  variance: True
  acceleration: False
  delta: False
  normalize: True
  slope: False
  limits: False
  csv: False

#Model training parameters
model_training:
  model_trainer: "sigtia_net"
  output_model: "sigtia_net.params"
  train_input_type: 'feature_matrix'
  ft_filter: 'linear'
  ft_nframes: 5
  ft_stack: True

svm_reg:
  balanced_class_weights: False
  num_workers: 12
  Cs: [1, 10, 100, 1000, 10000]
  gammas: [0.001, 0.0001, 0.00001, 0.000001]
  probability: False

sigtia_net:
  hidden_neurons: 50
  hidden_layers: 3
  dropout_rate: 0.0
  batch_size: 500
  max_epochs: 10000
  early_stopping: 500

gmm:
  num_workers: 4
  n_components: -1
  n_init: 5
  covariance_type: 'diag'
  min_covar: 0.01

hmm:
  n_components: 6
  covariance_type: 'diag'
  n_iter: 10
  n_workers: 1

#Model testing parameters
model_testing:
  model_tester: "simple"
  predict_proba_file: ""
  test_input_type: 'feature_matrix'
  label_dict: 'gtzan_label.dict'

voting:
  aggregation_type: 'max'
  votes: 5

#Evaluation parameters
evaluation:
  evaluator: "simple"
